# -*- coding: utf-8 -*-
"""IBDAlgoexp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TA0lQMK0kFdxb0c_OVTAgxQAWMmne2NL
"""

from google.colab import drive
drive.mount('/content/drive')
!pip install pysam
import pysam
import pandas as pd
import os
!apt-get update -qq
!apt-get install -y bcftools tabix
!pip install pysam
import numpy as np
import matplotlib.colors as mcolors
from matplotlib.patches import Patch
import matplotlib.pyplot as plt
import subprocess
vcf_path = "/content/drive/MyDrive/1000Genome/NonPruned_VCFs/siblings_merged.vcf.gz"
vcf_path_tbi = "/content/drive/MyDrive/1000Genome/NonPruned_VCFs/siblings_merged.vcf.gz.tbi"

sample1 = "HG00501"
sample2 = "HG00524"



MIN_AF = 0.05
BLOCK_SIZE = 1000
SMOOTH = 0.01
EPS = 1e-300

def is_biallelic_snp(rec):
    alts = rec.alts or ()
    if len(alts) != 1:
        return False
    if len(rec.ref) != 1:
        return False
    if len(alts[0]) != 1:
        return False
    return True

def get_af(rec):
    af = rec.info.get("AF")
    if af is None:
        return None
    if isinstance(af, (tuple, list)):
        if len(af) == 0:
            return None
        af = af[0]
    try:
        af = float(af)
    except:
        return None
    return af

def ibs_category(gt_a, gt_b):
    if gt_a is None:
        return None
    if gt_b is None:
        return None
    if None in gt_a:
        return None
    if None in gt_b:
        return None
    a = tuple(sorted(gt_a))
    b = tuple(sorted(gt_b))
    if a == b:
        return 2
    if a == (0, 0) and b == (1, 1):
        return 0
    if a == (1, 1) and b == (0, 0):
        return 0
    return 1

def emission_probs_smoothed(p):
    q = 1.0 - p
    p0_0 = 2.0 * (p * p) * (q * q)
    p2_0 = (q ** 4) + 4.0 * (p * p) * (q * q) + (p ** 4)
    p1_0 = 1.0 - p0_0 - p2_0
    ibd0 = np.array([p0_0, p1_0, p2_0], dtype=float)
    ibd1 = np.array([SMOOTH, 2.0 * p * q, p * p + q * q], dtype=float)
    ibd1 = ibd1 / ibd1.sum()
    ibd2 = np.array([SMOOTH, SMOOTH, 1.0], dtype=float)
    ibd2 = ibd2 / ibd2.sum()
    return ibd0, ibd1, ibd2

vcf = pysam.VariantFile(vcf_path)

rows = []
for rec in vcf:
    if not is_biallelic_snp(rec):
        continue
    af = get_af(rec)
    if af is None:
        continue
    maf = af
    if maf > 0.5:
        maf = 1.0 - maf
    if maf < MIN_AF:
        continue
    s1 = rec.samples.get(sample1)
    s2 = rec.samples.get(sample2)
    if s1 is None:
        continue
    if s2 is None:
        continue
    gt1 = s1.get("GT")
    gt2 = s2.get("GT")
    obs = ibs_category(gt1, gt2)
    if obs is None:
        continue
    chrom = str(rec.chrom)
    pos = int(rec.pos)
    rows.append((chrom, pos, maf, obs))

df = pd.DataFrame(rows, columns=["chrom", "pos", "maf", "ibs_obs"])
print("SNPs used:", len(df))

n = len(df)
n_blocks = (n + BLOCK_SIZE - 1) // BLOCK_SIZE
block_states = np.zeros(n_blocks, dtype=int)
block_chr = []
block_pos = []

for b in range(n_blocks):
    start = b * BLOCK_SIZE
    end = (b + 1) * BLOCK_SIZE
    if end > n:
        end = n
    block = df.iloc[start:end]
    first_row = block.iloc[0]
    block_chr.append(first_row["chrom"])
    block_pos.append(int(first_row["pos"]))
    logL0 = 0.0
    logL1 = 0.0
    logL2 = 0.0
    for i in range(len(block)):
        row = block.iloc[i]
        p = float(row["maf"])
        obs = int(row["ibs_obs"])
        ibd0, ibd1, ibd2 = emission_probs_smoothed(p)
        logL0 += np.log(max(ibd0[obs], EPS))
        logL1 += np.log(max(ibd1[obs], EPS))
        logL2 += np.log(max(ibd2[obs], EPS))
    best = np.argmax([logL0, logL1, logL2])
    block_states[b] = best

bounds = []
for i in range(1, n_blocks):
    if block_chr[i] != block_chr[i - 1]:
        bounds.append(i)

arr = block_states.reshape(1, n_blocks)

fig, ax = plt.subplots(figsize=(16, 1.8))
im = ax.imshow(arr, aspect="auto", interpolation="nearest", vmin=0, vmax=2)
ax.set_yticks([])
ax.set_xlabel(str(BLOCK_SIZE) + "-SNP blocks")
ax.set_title(sample1 + " vs " + sample2 + " IBD states")

for i in bounds:
    ax.axvline(i - 0.5)

cbar = fig.colorbar(im, ax=ax, fraction=0.03, pad=0.02)
cbar.set_ticks([0, 1, 2])
cbar.set_ticklabels(["IBD0", "IBD1", "IBD2"])

plt.tight_layout()
plt.show()

def window_smooth(states, win=10, thr0=0.50, thr12=0.80):
    s = np.asarray(states, dtype=int)
    out = s.copy()
    n = len(s)
    for i in range(0, n - win + 1):
        w = s[i:i+win]
        f0 = np.mean(w == 0)
        f1 = np.mean(w == 1)
        f2 = np.mean(w == 2)
        if f0 > thr0:
            out[i:i+win] = 0
            continue
        if f1 >= thr12:
            out[i:i+win] = 1
            continue
        if f2 >= thr12:
            out[i:i+win] = 2
            continue
    return out

states = arr.flatten()
smoothed = window_smooth(states, win=10, thr0=0.50, thr12=0.80)

raw = np.asarray(states, dtype=int)
smooth = np.asarray(smoothed, dtype=int)
total = len(smooth)

colors = ["purple","turquoise","yellow"]
cmap = mcolors.ListedColormap(colors)
bounds = [-0.5,0.5,1.5,2.5]
norm = mcolors.BoundaryNorm(bounds, cmap.N)

fig, axes = plt.subplots(2,1,figsize=(16,2.6),sharex=True)

axes[0].imshow(raw[None,:],aspect="auto",interpolation="nearest",cmap=cmap,norm=norm)
axes[0].set_yticks([])
axes[0].set_title("Before")

im = axes[1].imshow(smooth[None,:],aspect="auto",interpolation="nearest",cmap=cmap,norm=norm)
axes[1].set_yticks([])
axes[1].set_title("After")

plt.tight_layout()

cbar = fig.colorbar(im,ax=axes,orientation="horizontal",pad=0.25)
cbar.set_ticks([0,1,2])
cbar.set_ticklabels(["IBD0","IBD1","IBD2"])

plt.show()

def chrom_key(c):
    c = str(c).replace("chr", "")
    if c in ("X","x"):
        return 23
    if c in ("Y","y"):
        return 24
    if c in ("M","MT","m","mt"):
        return 25
    return int(c)

df2 = df.copy()
df2["chrom_num"] = df2["chrom"].map(chrom_key)
df2 = df2.sort_values(["chrom_num","pos"]).reset_index(drop=True)

df2["snp_idx"] = np.arange(len(df2))
df2["block"] = (df2["snp_idx"] // BLOCK_SIZE).astype(int)

smoothed = np.asarray(smoothed, dtype=int)
df2["ibd_state"] = smoothed[df2["block"].values]

chr_max = df2.groupby("chrom_num")["pos"].max().sort_index()
chr_offset = chr_max.cumsum().shift(fill_value=0)
df2["genome_pos"] = df2["pos"] + df2["chrom_num"].map(chr_offset)

blocks = df2.groupby(["block","chrom_num","chrom"]).agg(
    start_pos=("pos","first"),
    end_pos=("pos","last"),
    start_genome_pos=("genome_pos","first"),
    end_genome_pos=("genome_pos","last"),
    ibd_state=("ibd_state","first"),
).reset_index()

blocks["bp_span_chr"] = blocks["end_pos"] - blocks["start_pos"]
blocks["bp_span_genome"] = blocks["end_genome_pos"] - blocks["start_genome_pos"]

bp_by_state = blocks.groupby("ibd_state")["bp_span_chr"].sum()
bp_total = bp_by_state.sum()
pct_by_state = 100.0 * bp_by_state / bp_total


fig, ax = plt.subplots(figsize=(16,2.2))

colors = {0:"purple",1:"turquoise",2:"yellow"}

for _, r in blocks.iterrows():
    x0 = float(r["start_genome_pos"])
    w = float(r["bp_span_genome"])
    if w < 1:
        w = 1
    state = int(r["ibd_state"])
    ax.broken_barh([(x0,w)], (0,1), facecolors=[colors[state]])

for cn in sorted(df2["chrom_num"].unique()):
    chr_start = df2.loc[df2["chrom_num"]==cn, "genome_pos"].min()
    ax.axvline(chr_start, linewidth=1)

ax.set_yticks([])
ax.set_xlabel("Genome coordinate (bp; chromosomes concatenated)")
ax.set_title(f"IBD states by {BLOCK_SIZE}-SNP blocks (width = bp span)")

legend_elements = [
    Patch(facecolor="purple", label="IBD0"),
    Patch(facecolor="turquoise", label="IBD1"),
    Patch(facecolor="yellow", label="IBD2"),
]
ax.legend(handles=legend_elements, loc="upper right")

plt.tight_layout()
plt.show()

print("Percent bp covered (within-chrom spans):")
for k in (0,1,2):
    pct = float(pct_by_state.get(k, 0.0))
    print(f"  IBD{k}: {pct:.2f}%")